global:
 scrape_interval:     15s
 evaluation_interval: 15s

 external_labels:
     monitor: 'codelab-monitor'

rule_files:

scrape_configs:
 - job_name: 'prometheus'

   static_configs:
     - targets: ['localhost:9090'] # URL docker do prometheus

 - job_name: 'docker'
   metrics_path: '/actuator/prometheus'
   static_configs:
     - targets: ['192.168.2.6:8080'] # Onde ip = ip da sua máquina e port = porta da aplicação